# Generated by Django 5.0.6 on 2024-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_boleta_photocard_precio_alter_photocard_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocard',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
